project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Suhrud Kulkarni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: writing.qmd
        text: Writing
    right:
      - icon: github
        href: https://github.com/SuhrudKulkarni
      - icon: linkedin
        href: https://www.linkedin.com/in/suhrud-kulkarni-3a820488
      - text: Strava
        href: https://www.strava.com/athletes/25074162

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap
    html-math-method: mathjax
