project:
  type: website
  output-dir: _site

website:
  title: "Suhrud Kulkarni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: writing.qmd
        text: Writing
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/SuhrudKulkarni

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap
    html-math-method: mathjax
